### ISSUE TITLE
Question about docs/spec

### ISSUE THREAD

**Issue by ebuchman** [confio/ics23#108]
Should this:

https://github.com/confio/ics23/blob/f90dd766c44a3ce8be3f6765edc4f2f60967f6c1/proofs.proto#L104

Say

`hkey = hash(preHashKey)`

**Comment by ebuchman** [comment]
Oh nevermind - `prehashKey` is itself a function

**Comment by plafer** [comment]
It also confused me on the first read. Perhaps we should rewrite as

```js
hkey = LeafOp.prehash_key(key) 
```
or something along those lines? It's not perfect since `prehash_key` is an index into a table of hash functions, but probably better than the current comment?
