### ISSUE TITLE
Notes from review

### ISSUE THREAD

**Issue by cwgoes** [confio/ics23#25]
Generally this looks fantastic.

- Interfaces look fine, compliant with ICS 23 function signatures
- New hash functions can easily be added in a backwards-compatible way - :+1: 
- Cross-language test vectors - :+1: 
- `ProofSpec`s can more easily be stored in clients due to recent changes in ICS 2
- What is the "TODO" on `InnerSpec` - https://github.com/confio/ics23/blob/master/go/proofs.pb.go#L747 ?
- Do you have any suggestions for ICS 23?

I'll also note that ICS 2 has been restructured in a way conducive to custom client code defined at time of client creation (e.g. in WASM), so non-standard Ethereum proofs could potentially be supported that way.

Also left a few comments on https://github.com/confio/ics23/pull/24#pullrequestreview-279461688.

cc @mossid

**Comment by ethanfrey** [comment]
Moving some comments here from #24 as to suggestions for ICS23 spec:

One point is that there is no such function as VerifyMembership(proof, key, value). It needs to know the context of the type of tree. You could rewrite it to example:
`VerifyMembership: (spec) => (proof, key, value) => bool`
or anything else, but capturing some spec (definition of a particular merkle format) is critical, especially for non-membership proofs.

The idea of range/batch/neighbor calculations can definitely be expanded.

You may note that I expose non-membership proofs for stores that only themselves have a membership proof (ics23-tendermint). If the underlying store is ordered by key, we can produce all kinds of proofs, with a bunch of processing (client-side?) on the native proof format.

I'd be happy for more discussion on the ics23 spec, informed by what is built here (and what seems easy/hard to add).

**Comment by ethanfrey** [comment]
The TODO on the InnerSpec was to validate if this made sense, but then I did code it and it worked. To properly test it, I need test vectors were the branch ordering is not the same as the proof ordering.

eg. merk hashes (left branch || right branch || key-value) since the node stores the value between left and right, the `child_order` would be `[0, 2, 1]`. Which is the key purpose of the `child_order` field and definitely needs to be tested (one the merk codebase finished the rewrite and stabilizes).

**Comment by ebuchman** [comment]
Looks like great work, thanks Frey. Some questions:

- How were the test vectors generated?
- Is it worth trying to align at all with IPLD multishash/serialization standards efforts?
- On first glance it looks like the expected encoding of leaves is hand composed concatenations - is this general enough to eg capture a proto encoded leaf? Does it just mean the eg. field numbers and typ3 etc. would be incorporated into the length prefix ? 

A bit concerned that we might be trying to generalize too far or that there will be serious limits to this approach, as we're already seeing for the patricia tree and possibly for sparse merkle trees too (which iiuc encode keys in the path through the tree as well). How do we expect to deal with these kind of issues? Might we not just need to deal with tree-specific code in the end anyways, and if so, will the current generalization really be worth it? Maybe this effort can at least help guide us in the design of future trees (or re-design of current ones) that can better lend themselves to a somewhat generalized verification scheme ...

**Comment by ethanfrey** [comment]
Thanks for the feedback @ebuchman I will reply to each point in a separate comment - I wish there were threads in these issues, but at least I can get separate emojis for each point :smile:

**Comment by ethanfrey** [comment]
> How were the test vectors generated?

I should add to the readme file, but to answer this, they come from `make testgen` from https://github.com/confio/ics23-iavl and https://github.com/confio/ics23-tendermint (See [iavl Makefile](https://github.com/confio/ics23-iavl/blob/master/Makefile#L15) and [tendermint Makefile](https://github.com/confio/ics23-tendermint/blob/master/Makefile#L15)

**Comment by ethanfrey** [comment]
> Is it worth trying to align at all with IPLD multishash/serialization standards efforts?

I assume you refer to https://multiformats.io/multihash/ which could replace the use of [HashOp](https://github.com/confio/ics23/blob/master/proofs.proto#L5-L13) in the protobuf spec.

I don't see these as the same, as `multihash` encodes `<hash type><hashed length><hash>`, while we encode the preimage data - so this is a different format (they encode result, we encode how to calculate the result).

What would be doable in this respect is to standarize the integers used in the enum for the different operations to match their [multicodec table](https://github.com/multiformats/multicodec/blob/master/table.csv). In particular, the subset that have `tag = multihash`. There are many, many types for blake2b, blake2s, skein and some other formats that we don't need to implement yet (imo). However, we can use the same numbers for those we do implement.

Interestingly, this table does not list ripemd160 (even though it does have md4 and md5!) not the bitcoin hash algorithm (sha256 + ripemd160) which seem useful to support. I could make a request to add them to the table.

**Comment by ethanfrey** [comment]
> On first glance it looks like the expected encoding of leaves is hand composed concatenations - is this general enough to eg capture a proto encoded leaf? Does it just mean the eg. field numbers and typ3 etc. would be incorporated into the length prefix ? What if other information is encoded in a leaf beyond just the key and value, like maybe something about the tree structure for an iavl tree which is insertion-order-dependent) ?

I don't fully understand the question, but if you are talking about how the [LeafOp](https://github.com/confio/ics23/blob/master/proofs.proto#L109-L117) determines the leaf hash from key and value? There is a space for a prefix, which the Spec can enforce to start with a particular set of bytes (eg. iavl uses 0 for leaf and 1 for inner). 

In particular, we capture the encoding of [iavl leafs here](https://github.com/confio/ics23-iavl/blob/master/convert.go#L27-L39) which are `0x0002<amino encoded version>`. It turns out amino is using protobuf sint64 encoding here, which is double the integer and then encode it (which is designed to support small negative numbers well). The checker accepts any prefix that starts with `0x00`, and I could even make it stricter to enforce `0x0002`.

Is this clear? It seems like better docs are needed... particularly geared to adding support to another format

**Comment by ethanfrey** [comment]
> A bit concerned that we might be trying to generalize too far or that there will be serious limits to this approach, as we're already seeing for the patricia tree and possibly for sparse merkle trees too (which iiuc encode keys in the path through the tree as well). How do we expect to deal with these kind of issues? Might we not just need to deal with tree-specific code in the end anyways, and if so, will the current generalization really be worth it? Maybe this effort can at least help guide us in the design of future trees (or re-design of current ones) that can better lend themselves to a somewhat generalized verification scheme ...

I have done some reflection on this. This format should handle all cases where the key and value are present in the leaf hash calculation. The ethereum patricia trie format is a nasty mess (please look at https://github.com/confio/proofs-ethereum The sparse merkle tree is much cleaner design and could be supported by some generic algorithm. However, I do agree including it in this design would be generalizing too much, and I don't have any other examples of keys encoded in path designs in use of other blockchains. If you have a list, maybe we could make a related format to support them all - one for key-value in leaf, one for value in leaf + key in path.


In terms of utility, maybe ics23 will have to support store specific code. However, even at the current state, I think this represents a large advance for the iavl and tendermint map proofs. There is custom logic - especially in iavl range proofs - which is embedded in much unexported go code. Parsing and verifying those in pure js (or rust) land is a huge challenge, and I think unspec'd go-only codecs are no longer viable in the interchain world. With a relatively small amount of go code, we can create standardized merkle proofs that can be parsed in 3 languages, with a clearly defined format. If nothing else, I feel this should be *one* supported proof format for ics, and one exported by cosmos-sdk.

**Comment by cwgoes** [comment]
Additional notes: https://github.com/cosmos/ics/issues/282#issuecomment-589690471.

**Comment by ethanfrey** [comment]
Great, I will implement these changes, let me know current timelines for the ibc implementation so I can properly prioritize it

**Comment by cwgoes** [comment]
Subsumed by https://github.com/confio/ics23/pull/28.
