### ISSUE TITLE
Unable to use Go releases with go.mod

### ISSUE THREAD

**Issue by erikgrinaker** [confio/ics23#35]
Trying to use ics23 releases in IAVL, by putting this in `go.mod`:

```
require (
	github.com/confio/ics23 v0.6.3
)
```

Gives a `go mod tidy` error when importing like this:

```
import (
  ics23 "github.com/confio/ics23/go"
)
```

> github.com/confio/ics23/go is not in your go.mod file

Changing the `go.mod` module to include `/go` fails because the module does not have a v0.6.3 release, and changing the import to not use `/go` fails because there is no Go package at that path.

**Comment by erikgrinaker** [comment]
CC @AdityaSripal

**Comment by ethanfrey** [comment]
Yeah, I have no idea how to improve this. I try to keep language independent dirs under root, and go is the only one complaining. 

If you figure out a better way to handle go.mod, please make a pr and mention me. I'm more than happy to merge. (I spent some time with this when setting up the repo... that was go 1.12 or 1.13 so maybe things have changed)

**Comment by zmanian** [comment]
My understanding of the issue is the release tag needs to have sub-directory in it.

so instead of `v0.6.3` it would be `go/v0.6.3`

**Comment by erikgrinaker** [comment]
I tested this with a sandbox repo, there are two options:

1. Like @zmanian says, use an additional tag `go/v0.6.3` for each release to work around this.

2. Move `go/go.mod` to the root, and call the module `github.com/confio/ics23`. It must still be imported as `github.com/confio/ics23/go` in source files, but referenced as `github.com/confio/ics23` in the consumer's `go.mod`.

Personally I feel like 2 is the lesser of evils, especially since there's already a proxy `go.mod` in the root, but your call @ethanfrey.

**Comment by ethanfrey** [comment]
I did try 2 before, and go mod made the 2 mod setup. This was not my idea, but I didn't spend a lot of time investigating it.

I tagged `go/v0.6.3` as per Zaki's request, I should add some info about this to the README I guess

**Comment by zmanian** [comment]
I think this issue can be closed

**Comment by erikgrinaker** [comment]
Yeah, I can use version tags in `go.mod` now, so I'm happy. Thanks guys!
