### ISSUE TITLE
Sec advisory for generic-array dependency

### ISSUE THREAD

**Issue by adizere** [confio/ics23#37]
It seems that the dependency `generic-array` v0.12.3 for the Rust version of ICS23 is outdated and risky:

https://github.com/confio/ics23/blob/f173e6211efbf546bf9fcdc5cc29e5e055151666/rust/Cargo.lock#L134-L136

https://rustsec.org/advisories/RUSTSEC-2020-0146.html

We found this out through a [cargo audit](https://github.com/informalsystems/ibc-rs/runs/2012198767?check_suite_focus=true) on ibc-rs.

**Comment by ethanfrey** [comment]
I am pretty sure that we don't use `arr!` anywhere. But I would be happy to merge a PR with updated dependencies

**Comment by adizere** [comment]
Fixed in https://github.com/confio/ics23/pull/38
