### ISSUE TITLE
compress: avoid []byte->string penalty conversion for key to hashmap

### ISSUE THREAD

**Issue by odeke-em** [confio/ics23#45]
We periodically do supply chain analyses for code that goes into cosmos/cosmos-sdk and that entails security and performance auditing.

I noticed this code https://github.com/confio/ics23/blob/5a0206f31ac5ccb40757e98a3c86e7beff95793b/go/compress.go#L96-L106

which when examined, if using say 1.50MiB of RAM, consumes about 33% of the memory just from the []byte->string conversion which is as much RAM as invoking step.Marshal()
```python
ROUTINE ======================== github.com/confio/ics23/go.compressStep in /Users/emmanuelodeke/go/src/github.com/confio/ics23/go/compress.go
       1MB     1.50MB (flat, cum)  1.13% of Total
         .          .     87:	}
         .          .     88:	return res
         .          .     89:}
         .          .     90:
         .          .     91:func compressStep(step *InnerOp, lookup *[]*InnerOp, registry map[string]int32) int32 {
         .   512.02kB     92:	bz, err := step.Marshal()
         .          .     93:	if err != nil {
         .          .     94:		panic(err)
         .          .     95:	}
  512.02kB   512.02kB     96:	sig := string(bz)
         .          .     97:
         .          .     98:	// load from cache if there
         .          .     99:	if num, ok := registry[sig]; ok {
         .          .    100:		return num
         .          .    101:	}
         .          .    102:
         .          .    103:	// create new step if not there
         .          .    104:	num := int32(len(*lookup))
  512.12kB   512.12kB    105:	*lookup = append(*lookup, step)
         .          .    106:	registry[sig] = num
         .          .    107:	return num
         .          .    108:}
         .          .    109:
         .          .    110:func decompress(comp *CompressedBatchProof) *BatchProof {
```

and as you can imagine if this code gets hit a whole lot, that multiplies. The solution is very simple.

## Solution
Please use the map key idiom in which that code turns into `if num, ok := registry[string(bz)]` and `registry[string(bz)] = num`

/cc @cuonglm @marbar3778 @alexanderbez @ethanfrey to remind us to make a version update to include in the cosmos-sdk when this update is made. Thank you

**Comment by cuonglm** [comment]
@odeke-em Note that the optimization is only applied for map get/delete. For map assignment, the compiler must introduce temporary and cannot perform optimization.

**Comment by odeke-em** [comment]
> @odeke-em Note that the optimization is only applied for map get/delete. For map assignment, the compiler must introduce temporary and cannot perform optimization.

Oh right, I forgot that, the Go compiler is kind of still primitive because it should recognize that that byte slice doesn't escape nor is it used out of the function therefore it should apply that optimization. We can file a bug for this and perhaps improve it in Go1.18. For now I'll actually handle this and mail out the change removing that allocation.

**Comment by odeke-em** [comment]
Actually given that the string won't be used anymore, it'll be attached to dangling memory so it has to pay the penalty, never mind :-)

**Comment by odeke-em** [comment]
Closing this issue as irrelevant as there is nothing we can do, we have to pay that penalty either way.

**Comment by ethanfrey** [comment]
So this is expensive code we cannot optimize?

Compress can be called on a client, where decompress must be called on the blockchain node. I'd love to see an analysis of that code. Maybe a Simple pr to mention these issues as godoc?

**Comment by cuonglm** [comment]
> > @odeke-em Note that the optimization is only applied for map get/delete. For map assignment, the compiler must introduce temporary and cannot perform optimization.
> 
> Oh right, I forgot that, the Go compiler is kind of still primitive because it should recognize that that byte slice doesn't escape nor is it used out of the function therefore it should apply that optimization. We can file a bug for this and perhaps improve it in Go1.18. For now I'll actually handle this and mail out the change removing that allocation.

No, the thing is that the `registry` is an argument to the function, so it outlives the function scope. Just the key must be heap allocated.
