### ISSUE TITLE
The prefix between the leaf spec and an inner op

### ISSUE THREAD

**Issue by yito88** [confio/ics23#51]
Why should the prefix of the leaf spec be different from that of inner op?
https://github.com/confio/ics23/blob/5a0206f31ac5ccb40757e98a3c86e7beff95793b/rust/src/verify.rs#L147

In a merkle tree I'm using, both the leaf prefix and that of the inner are not used.

**Comment by ethanfrey** [comment]
> In a merkle tree I'm using, both the leaf prefix and that of the inner are not used.

Check with GitHub.com/tendermint/iavl as to the design criteria. There is some (at least theoretical) attack vector if you can trick a proof to believe an inner node is actually a leaf. And most implementations I have seen have used something to differentiate them.

Can you link your implementation?

This logic is also in the Go code on many Cosmos chains, so very hard to change this without a major breaking upgrade.

**Comment by yito88** [comment]
Thank you for the explanation!
I'm using [sparse-merkle-tree](https://github.com/nervosnetwork/sparse-merkle-tree).

**Comment by ethanfrey** [comment]
Thanks for the link. I just saw 

> Notice this library is not stabled yet. The API and the format of the proof may be changed in the future. Make sure you know what you are doing before using this library.

Maybe they can change?

(But if this is also how the Ethereum SMT is built, then compatibility is probably even more important)

**Comment by yito88** [comment]
It looks better to change the tree for the tolerance against the attacks.
Thanks!
