### ISSUE TITLE
Please yank 0.7.1 of the `ics23` crate and re-release as 0.8.0

### ISSUE THREAD

**Issue by hdevalence** [confio/ics23#87]
The `0.7.1` release of the `ics23` crate is marked as a semver-compatible point release from `0.7.0`, but changes the `prost` version in the public API from `0.9` to `0.10`, which is a breaking change.

Please yank it, and re-release it as `0.8.0`, so that crates that were depending on the existing version will compile again.

**Comment by ethanfrey** [comment]
This was requested to come out quickly, so I made a minor release.
 I wanted to go through all issues before making a proper 0.8.0.

I just yanked `0.7.1` and re-released it as `0.8.0-alpha`. Hope this fixes those issues

**Comment by hdevalence** [comment]
@ethanfrey thanks so much!
